"use client";

import { useState } from "react";
import Link from "next/link";

interface AlgorithmCard {
  id: string;
  name: string;
  type: "DETECTOR" | "MATCHER" | "ESTIMATOR" | "TRANSFORM";
  description: string;
  mathFormula: string;
  inlierRate: string;
  rmse: string;
  runtime: string;
  features: string[];
}

const algorithms: AlgorithmCard[] = [
  {
    id: "sift",
    name: "Scale-Invariant Feature Transform (SIFT)",
    type: "DETECTOR",
    description:
      "Computes extrema in scale-space generated by Difference-of-Gaussians (DoG). Invariant to scale, rotation, and illumination gradients prevalent in low-angle lunar topography.",
    mathFormula: "D(x, y, \\sigma) = (G(x, y, k\\sigma) - G(x, y, \\sigma)) * I(x, y)",
    inlierRate: "92.4%",
    rmse: "0.54 px",
    runtime: "820 ms",
    features: ["Scale-Space Octaves: 4", "Contrast Threshold: 0.04", "Edge Threshold: 10.0", "128-D Descriptors"],
  },
  {
    id: "akaze",
    name: "Accelerated KAZE (A-KAZE)",
    type: "DETECTOR",
    description:
      "Exploits non-linear scale space using Fast Explicit Diffusion (FED). Preserves lunar crater boundaries, steep rim shadows, and fine boulder textures without blurring sharp morphological edges.",
    mathFormula: "\\frac{\\partial L}{\\partial t} = \\text{div}(c(x, y, t) \\cdot \\nabla L)",
    inlierRate: "94.1%",
    rmse: "0.49 px",
    runtime: "640 ms",
    features: ["Nonlinear Scale Space", "M-LDB Binary Descriptor", "FED Step Integrator", "Sub-pixel Extrema Refinement"],
  },
  {
    id: "superpoint",
    name: "SuperPoint Deep Keypoint Network",
    type: "DETECTOR",
    description:
      "Self-supervised convolutional neural network trained on synthetic homographies. Extracts robust repeatability on low-texture lunar regolith under varying solar azimuth angles.",
    mathFormula: "\\mathcal{L}_{p}(X, Y) = -\\sum_{i} \\log P(Y_i | X_i)",
    inlierRate: "96.5%",
    rmse: "0.42 px",
    runtime: "280 ms (GPU)",
    features: ["TensorRT / PyTorch Backend", "256-D Semi-Dense Embedding", "Homographic Adaptation", "A100 Tensor Core Optimized"],
  },
  {
    id: "magsac",
    name: "MAGSAC++ (Marginalized Sample Consensus)",
    type: "ESTIMATOR",
    description:
      "Eliminates hard inlier/outlier thresholding by marginalizing over a continuous residual noise range. Produces mathematically optimal homography matrices on lunar crater terrain.",
    mathFormula: "P(\\text{inlier} | r) = \\int_0^{\\infty} p(r | \\sigma) p(\\sigma) d\\sigma",
    inlierRate: "98.2%",
    rmse: "0.38 px",
    runtime: "120 ms",
    features: ["Threshold-free Optimization", "Chi-squared Distribution Fitting", "Sub-pixel Covariance", "Guaranteed Convergence"],
  },
  {
    id: "homography",
    name: "Planar Projective Homography (8 DOF)",
    type: "TRANSFORM",
    description:
      "Maps planar lunar surface points between sensor perspectives under high orbital altitude assumptions. Handles projective foreshortening between oblique and nadir frames.",
    mathFormula: "s \\begin{bmatrix} x' \\\\ y' \\\\ 1 \\end{bmatrix} = \\begin{bmatrix} h_{11} & h_{12} & h_{13} \\\\ h_{21} & h_{22} & h_{23} \\\\ h_{31} & h_{32} & 1 \\end{bmatrix} \\begin{bmatrix} x \\\\ y \\\\ 1 \\end{bmatrix}",
    inlierRate: "93.8%",
    rmse: "0.52 px",
    runtime: "15 ms",
    features: ["8 Degrees of Freedom", "DLT + Levenberg-Marquardt", "Sub-pixel Bicubic Warping", "Inverse Compositional Formulation"],
  },
  {
    id: "tps",
    name: "Thin-Plate Spline (TPS) Deformation Model",
    type: "TRANSFORM",
    description:
      "Non-rigid interpolation model simulating bending of an elastic thin sheet. Compensates for significant lunar elevation variations and parallax over deep crater basins (e.g. Shackleton).",
    mathFormula: "f(x, y) = a_1 + a_x x + a_y y + \\sum_{i=1}^n w_i U(\\|(x,y) - P_i\\|)",
    inlierRate: "97.4%",
    rmse: "0.35 px",
    runtime: "190 ms",
    features: ["Bending Energy Minimization", "Radial Basis Kernels", "Local Relief Compensation", "Elevation Differential Smoothing"],
  },
];

export default function AnalysisMethodsPage() {
  const [selectedType, setSelectedType] = useState<string>("ALL");
  const [activeAlgoId, setActiveAlgoId] = useState<string>("sift");

  const filtered = algorithms.filter((a) => selectedType === "ALL" || a.type === selectedType);
  const activeAlgo = algorithms.find((a) => a.id === activeAlgoId) || algorithms[0];

  return (
    <div className="flex flex-col w-full gap-space-md py-space-sm font-body-md pb-space-2xl">
      {/* Breadcrumb */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-space-xs font-mono-data-sm text-mono-data-sm text-on-surface-variant">
          <Link href="/dashboard" className="hover:text-secondary">ISRO Portal</Link>
          <span>/</span>
          <span>Methods</span>
          <span>/</span>
          <span className="text-secondary font-semibold">Analysis Methods</span>
        </div>
        <span className="px-space-xs py-space-2xs bg-surface-container rounded font-mono-data-sm text-mono-data-sm text-on-surface">
          SPECIFICATION: <strong className="text-secondary">PDS-4 CV/ML KERNEL v2.4</strong>
        </span>
      </div>

      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-baseline justify-between gap-space-sm">
        <div>
          <h1 className="font-headline-md text-headline-md text-on-surface uppercase font-bold tracking-tight">
            Algorithmic Pipeline &amp; Photogrammetric Methods
          </h1>
          <p className="text-body-sm text-on-surface-variant">
            Mathematical foundations, feature descriptors, robust consensus estimators, and transformation models for Chandrayaan-2/3 imagery.
          </p>
        </div>
        <Link
          href="/new-analysis"
          className="px-space-md py-2 bg-primary-container text-on-primary rounded hover:bg-secondary transition-colors font-body-sm font-semibold flex items-center gap-1.5 self-start shadow-sm"
        >
          <span className="material-symbols-outlined text-[16px]">play_arrow</span>
          <span>Run Pipeline with Method</span>
        </Link>
      </div>

      {/* Pipeline Stage Architecture Overview */}
      <div className="bg-primary-container text-white p-space-md rounded-xl shadow-sm flex flex-col gap-space-sm">
        <span className="font-label-caps text-label-caps uppercase tracking-wider text-secondary-container font-semibold">
          End-to-End Registration Pipeline Flow
        </span>
        <div className="grid grid-cols-1 sm:grid-cols-4 gap-space-sm font-mono-data-sm text-mono-data-sm">
          <div className="p-space-sm bg-black/30 rounded border border-white/10 flex flex-col gap-1">
            <span className="text-secondary-fixed text-xs font-bold">STAGE 1: RADIOMETRIC PREP</span>
            <span className="text-white text-body-sm font-semibold">Level-2B Calibration</span>
            <span className="text-on-primary-container text-[11px]">Dark current &amp; flat-field matrix</span>
          </div>
          <div className="p-space-sm bg-black/30 rounded border border-white/10 flex flex-col gap-1">
            <span className="text-secondary-fixed text-xs font-bold">STAGE 2: FEATURE EXTRACTION</span>
            <span className="text-white text-body-sm font-semibold">SIFT / AKAZE / SuperPoint</span>
            <span className="text-on-primary-container text-[11px]">Scale-space extrema &amp; descriptors</span>
          </div>
          <div className="p-space-sm bg-black/30 rounded border border-white/10 flex flex-col gap-1">
            <span className="text-secondary-fixed text-xs font-bold">STAGE 3: ROBUST CONSENSUS</span>
            <span className="text-white text-body-sm font-semibold">MAGSAC++ / USAC</span>
            <span className="text-on-primary-container text-[11px]">Marginalized outlier filtering</span>
          </div>
          <div className="p-space-sm bg-black/30 rounded border border-white/10 flex flex-col gap-1">
            <span className="text-secondary-fixed text-xs font-bold">STAGE 4: GEOMETRIC WARP</span>
            <span className="text-white text-body-sm font-semibold">Homography / TPS Spline</span>
            <span className="text-on-primary-container text-[11px]">Sub-pixel GeoTIFF raster export</span>
          </div>
        </div>
      </div>

      {/* Filter Chips */}
      <div className="flex items-center gap-2 overflow-x-auto pb-1">
        {(["ALL", "DETECTOR", "MATCHER", "ESTIMATOR", "TRANSFORM"] as const).map((t) => (
          <button
            key={t}
            onClick={() => setSelectedType(t)}
            className={`px-3 py-1.5 rounded-lg font-mono-data-sm text-xs font-semibold whitespace-nowrap transition-all ${
              selectedType === t
                ? "bg-secondary text-white shadow-xs"
                : "bg-surface-container text-on-surface-variant hover:text-on-surface"
            }`}
          >
            {t}
          </button>
        ))}
      </div>

      {/* Method Cards Grid & Selected Detail Inspector */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-space-md">
        {/* Cards List (7 cols) */}
        <div className="lg:col-span-7 flex flex-col gap-space-sm">
          {filtered.map((algo) => (
            <div
              key={algo.id}
              onClick={() => setActiveAlgoId(algo.id)}
              className={`p-space-md rounded-xl cursor-pointer transition-all border ${
                activeAlgoId === algo.id
                  ? "bg-surface-container-lowest border-secondary shadow-sm ring-1 ring-secondary"
                  : "bg-surface-container-lowest border-outline-variant/30 hover:border-secondary/50 shadow-xs"
              }`}
            >
              <div className="flex items-center justify-between mb-1">
                <div className="flex items-center gap-2">
                  <span className="px-2 py-0.5 rounded font-mono-data-sm text-[10px] font-bold uppercase bg-surface-container text-secondary">
                    {algo.type}
                  </span>
                  <span className="font-headline-sm text-headline-sm font-semibold text-on-surface">{algo.name}</span>
                </div>
                <span className="font-mono-data-sm text-xs font-bold text-[#065f46] bg-[#ecfdf5] px-2 py-0.5 rounded">
                  {algo.inlierRate} Inliers
                </span>
              </div>
              <p className="text-body-sm text-on-surface-variant mt-1 line-clamp-2">{algo.description}</p>
              <div className="flex items-center gap-4 mt-space-sm font-mono-data-sm text-xs text-on-surface-variant pt-2 border-t border-surface-container">
                <span>RMSE: <strong className="text-on-surface">{algo.rmse}</strong></span>
                <span>Runtime: <strong className="text-on-surface">{algo.runtime}</strong></span>
              </div>
            </div>
          ))}
        </div>

        {/* Algorithm Deep Inspector (5 cols) */}
        <div className="lg:col-span-5 bg-surface-container-lowest p-space-md rounded-xl shadow-sm border border-outline-variant/30 flex flex-col gap-space-md self-start">
          <div className="flex items-center justify-between border-b border-surface-container pb-space-sm">
            <div>
              <span className="font-label-caps text-label-caps uppercase text-secondary font-bold">Method Specification</span>
              <h2 className="font-headline-sm text-headline-sm text-on-surface font-semibold">{activeAlgo.name}</h2>
            </div>
            <span className="px-2 py-1 bg-surface-container rounded font-mono-data-sm text-xs font-bold text-on-surface">
              {activeAlgo.type}
            </span>
          </div>

          <div className="flex flex-col gap-1">
            <span className="font-label-caps text-label-caps uppercase text-on-surface-variant font-bold">Description</span>
            <p className="text-body-sm text-on-surface leading-relaxed">{activeAlgo.description}</p>
          </div>

          <div className="p-space-sm bg-primary-container/90 text-white rounded-lg flex flex-col gap-1 font-mono-data-sm text-xs">
            <span className="text-secondary-container font-label-caps text-label-caps uppercase font-bold">Mathematical Formulation</span>
            <code className="text-secondary-fixed select-all overflow-x-auto py-1">{activeAlgo.mathFormula}</code>
          </div>

          <div className="flex flex-col gap-1.5">
            <span className="font-label-caps text-label-caps uppercase text-on-surface-variant font-bold">Key Pipeline Parameters</span>
            <div className="grid grid-cols-1 gap-1.5 font-mono-data-sm text-xs">
              {activeAlgo.features.map((feat, idx) => (
                <div key={idx} className="px-3 py-1.5 bg-surface-container-low rounded text-on-surface flex items-center gap-2">
                  <span className="w-1.5 h-1.5 rounded-full bg-secondary"></span>
                  <span>{feat}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="pt-space-xs border-t border-surface-container flex items-center justify-between font-mono-data-sm text-xs text-on-surface-variant">
            <span>Accuracy: <strong className="text-[#065f46] font-bold">{activeAlgo.inlierRate}</strong></span>
            <span>Error: <strong className="text-secondary font-bold">{activeAlgo.rmse}</strong></span>
          </div>
        </div>
      </div>
    </div>
  );
}
